DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS ratings (
                                       rating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       rating_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                     film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     film_name VARCHAR(100) NOT NULL,
                                     description VARCHAR(200) NOT NULL,
                                     release_date DATE NOT NULL,
                                     duration INT NOT NULL,
                                     rating INT REFERENCES ratings(rating_id) ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS genres (
                                      genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      genre_name VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS film_genres (
                                    film_id BIGINT REFERENCES films(film_id),
                                    genre_id BIGINT REFERENCES genres(genre_id),
                                    PRIMARY KEY (film_id,genre_id)
);


CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(100) UNIQUE NOT NULL,
                                     login VARCHAR(100) UNIQUE NOT NULL,
                                     user_name VARCHAR(100),
                                     birthday DATE
);

CREATE TABLE IF NOT EXISTS friendship (
                                     user_id BIGINT REFERENCES users(user_id),
                                     friend_id BIGINT REFERENCES users(user_id),
                                     PRIMARY KEY (user_id,friend_id)
);

CREATE TABLE IF NOT EXISTS likes (

                                     film_id BIGINT REFERENCES films(film_id),
                                     user_id BIGINT REFERENCES users(user_id),
                                     PRIMARY KEY (film_id,user_id)
);

