DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS ratings (
                                       rating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       rating_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                     film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     film_name VARCHAR(100) NOT NULL,
                                     description VARCHAR(200) NOT NULL,
                                     release_date DATE NOT NULL,
                                     duration INT NOT NULL,
                                     rating INT REFERENCES ratings(rating_id) ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS genres (
                                      genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      genre_name VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS film_genres (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        film_id BIGINT NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
                                        genre_id BIGINT NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
                                        UNIQUE (film_id, genre_id)
);


CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(100) UNIQUE NOT NULL,
                                     login VARCHAR(100) UNIQUE NOT NULL,
                                     user_name VARCHAR(100),
                                     birthday DATE
);

CREATE TABLE IF NOT EXISTS friendship (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                                     friend_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                                     UNIQUE (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     film_id BIGINT NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
                                     user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                                     UNIQUE (film_id, film_id)
);

