DELETE FROM users;
INSERT INTO users (EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('user1@mail.ru', 'login1', 'user1', '2000-01-01');

INSERT INTO users (EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('user2@mail.ru', 'login2', 'user2', '2000-02-02');

INSERT INTO users (EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('user3@mail.ru', 'login3', 'user3', '2000-03-03');

DELETE FROM films;
INSERT INTO films (NAME, DESCRIPTION, RELEASEDATE, DURATION, RATING_MPA_ID, LIKES_COUNTER)
VALUES ('film1', 'description1', '2000-01-11', '2000', 1, 1);

INSERT INTO films (NAME, DESCRIPTION, RELEASEDATE, DURATION, RATING_MPA_ID, LIKES_COUNTER)
VALUES ('film2', 'description2', '2000-02-12', '2000', 2, 2);

INSERT INTO films (NAME, DESCRIPTION, RELEASEDATE, DURATION, RATING_MPA_ID, LIKES_COUNTER)
VALUES ('film3', 'description3', '2000-03-13', '2000', 3, 3);